INSERT INTO TB_ACAO (ID_ACAO, ATIVO, DESCRICAO, NOME) VALUES (ACAO_SEQ.NEXTVAL, 1, 'CHAPPIE COMECA A CORRER', 'CORRER');
INSERT INTO TB_ACAO (ID_ACAO, ATIVO, DESCRICAO, NOME) VALUES (ACAO_SEQ.NEXTVAL, 1, 'CHAPPIE INICIA SEU MODO SALVA VIDAS', 'SALVAR');
INSERT INTO TB_ACAO (ID_ACAO, ATIVO, DESCRICAO, NOME) VALUES (ACAO_SEQ.NEXTVAL, 1, 'CHAPPIE INICIA SEU MODO NATACAO', 'NADAR');

INSERT INTO TB_EXECUCAO (ID_EXECUCAO, DATA, ID_ACAO) VALUES (EXECUCAO_SEQ.NEXTVAL, '10/11/2020 15:30:20', 1);
INSERT INTO TB_EXECUCAO (ID_EXECUCAO, DATA, ID_ACAO) VALUES (EXECUCAO_SEQ.NEXTVAL, '11/11/2020 15:30:20', 2);
INSERT INTO TB_EXECUCAO (ID_EXECUCAO, DATA, ID_ACAO) VALUES (EXECUCAO_SEQ.NEXTVAL, '12/11/2020 15:30:20', 3);




